name: Deploy to AUR

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  aur-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.2
        with:
          pkgname: code-weaver
          pkgbuild: ./PKGBUILD
          commit_username: SoleilSaint
          commit_email: forevergoodforest@outlook.com
          ssh_private_key: ${{ secrets.AUR_PRIVATE_KEY }}
          commit_message: Update to ${{ github.event.release.tag_name }}
          ssh_keyscan_types: dsa,ecdsa,ed25519

          updpkgsums: true
