name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  rust:
    # 运行环境
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --locked

      - name: Test
        run: cargo test
