name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  rust:
    # 运行环境
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/code_weaver
